id: I6EFF9668
initial_creation_type: ebook
source_metadata:
  id: RDI-SK-08
  title: ལུས་སྦྱོང་འཕྲུལ་འཁོར་ཆ་ལག་ཀུན་གསལ་མེ་ལོང་།
  author: མཛད་པ་པོ། ཏཱ་ར་ནཱ་ཐ།
  authors: &id001
  - མཛད་པ་པོ། ཏཱ་ར་ནཱ་ཐ།
  sku: RDI-SK-08
  cover: RDI-SK-08.jpeg
  volume: {}
  series: ཤངས་པའི་རྣལ་འབྱོར་ཐེམ་སྐས་གདམས་ངག་ཕྱོགས་བསྒྲིགས།
  title_source: epub:dc:title:ambiguous-layer
ebook_metadata:
  title: ལུས་སྦྱོང་འཕྲུལ་འཁོར་ཆ་ལག་ཀུན་གསལ་མེ་ལོང་།
  authors: *id001
  sku: RDI-SK-08
  cover: RDI-SK-08.jpeg
layers:
- Author
- BookNumber
- BookTitle
- Chapter
- Citation
- Commentary
- Tsawa
- Yigchung
